(defvar diadara/packages '(smooth-scrolling
                           undo-tree
                           smex
                           multiple-cursors
                           expand-region
                           wrap-region
                           ido-vertical-mode
                           smartparens
                           ace-jump-mode
                           auto-complete
                           auto-indent-mode
                           bash-completion
                           cider
                           cl-lib
                           clojure-mode
                           clojure-test-mode
                           csv-mode
                           guru-mode
                           guide-key
                           dash
                           dired-details
                           edit-server
                           emmet-mode
                           fill-column-indicator
                           flymake
                           flymake-easy
                           git-commit-mode
                           gitconfig-mode
                           gitignore-mode
                           god-mode
                           haml-mode
                           handlebars-mode
                           httpcode
                           jedi
                           js2-mode
                           js2-refactor
                           json-mode
                           lorem-ipsum
                           magit
                           markdown-mode
                           org
                           projectile
                           python-pep8
                           python-pylint
                           rainbow-delimiters
                           rainbow-mode
                           yaml-mode))

(provide 'elpa-packages)
